# Railway configuration for Node.js backend API
[build]
builder = "nixpacks"
installCommand = "npm ci"
buildCommand = "echo 'No build step required for backend API'"

[deploy]
startCommand = "node server.js"
numReplicas = 1